# Install Dependencies

In [1]:
!pip install -q arxiv transformers sentence-transformers pandas scikit-learn streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 40.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 112.5 MB/s eta 0:00:00

# Imports

In [9]:
!pip install transformers torch

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.41.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers) (1.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2026.5.20)

In [1]:
import arxiv
import pandas as pd


from transformers import pipeline

# Fetch Papers from arXiv (FIXED API)

In [21]:
query = "artificial intelligence"



client = arxiv.Client(
    page_size=100,     # fetch 100 per request (max allowed by arXiv API)
    delay_seconds=3,   # polite delay to avoid rate-limiting
    num_retries=5      # retry on transient failures
)

papers = []

for result in client.results(client):
    papers.append({
        "title": result.title,
        "abstract": result.summary,
        "authors": ", ".join([a.name for a in result.authors]),
        "published": result.published,
        "pdf": result.pdf_url
    })

df = pd.DataFrame(papers)

df.head()

,title,abstract,authors,published,pdf
0,Lumos-Nexus: Efficient Frequency Bridging with...,Connector-based video unified models have demo...,"Jiazheng Xing, Hangjie Yuan, Lingling Cai, Xin...",2026-05-29 17:59:50+00:00,https://arxiv.org/pdf/2605.31603v1
1,Stateful Online Monitoring Catches Distributed...,Language models can find thousands of severe s...,"Davis Brown, Samarth Bhargav, Arav Santhanam, ...",2026-05-29 17:57:00+00:00,https://arxiv.org/pdf/2605.31593v1
2,TunerDiT: Training-free Progressive Steering o...,Text-to-video (T2V) generation faces challengi...,"Ruotong Liao, Guowen Huang, Qing Cheng, Guangy...",2026-05-29 17:56:09+00:00,https://arxiv.org/pdf/2605.31590v1
3,Language Models Learn Constructional Semantics...,Grasping the semantics of rare constructions (...,"Wesley Scivetti, Ethan Wilcox, Nathan Schneide...",2026-05-29 17:54:00+00:00,https://arxiv.org/pdf/2605.31586v1
4,LongTraceRL: Learning Long-Context Reasoning f...,Long-context reasoning remains a central chall...,"Nianyi Lin, Jiajie Zhang, Lei Hou, Juanzi Li",2026-05-29 17:51:40+00:00,https://arxiv.org/pdf/2605.31584v1

In [22]:
print(f"Total papers fetched: {len(df)}")

Total papers fetched: 200

# Load Summarizer

In [3]:
from transformers import pipeline

In [15]:
!pip uninstall -y transformers
!pip install transformers==4.41.1 accelerate torch sentencepiece

Found existing installation: transformers 4.41.1
Uninstalling transformers-4.41.1:
  Successfully uninstalled transformers-4.41.1
Collecting transformers==4.41.1
  Using cached transformers-4.41.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cpu)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (3.29.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (2.32.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.41.1) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.1) (1.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.41.1) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.41.1) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.41.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.41.1) (2026.5.20)
Using cached transformers-4.41.1-py3-none-any.whl (9.1 MB)
Installing collected packages: transformers
Successfully installed transformers-4.41.1

In [4]:
import transformers
print(transformers.__version__)

4.41.1

In [23]:
summarizer = pipeline(
    "summarization",
    model="sshleifer/distilbart-cnn-12-6"
)

# Create Safe Summarization Function

In [24]:
def summarize(text):
    try:
        text = str(text)
        text = text.replace("\n", " ")[:800]

        result = summarizer(text, max_length=120, min_length=30, do_sample=False)

        print("DEBUG OUTPUT:", result)

        return result[0]["summary_text"]

    except Exception as e:
        print("ERROR:", e)
        return "Summary failed"

In [25]:
summarize(df["abstract"].iloc[0])

DEBUG OUTPUT: [{'summary_text': ' Connector-based video unified models have demonstrated strong capability in instruction-grounded video synthesis . We propose Lumos-Nexus, a training-efficient unified video generation framework that facilitates the development of strong reasoning-driven generation capabilities while enhancing visual fidelity .'}]

' Connector-based video unified models have demonstrated strong capability in instruction-grounded video synthesis . We propose Lumos-Nexus, a training-efficient unified video generation framework that facilitates the development of strong reasoning-driven generation capabilities while enhancing visual fidelity .'

# Apply Summarization on DataFrame

In [26]:
from tqdm import tqdm

tqdm.pandas()

df["summary_generated"] = df["abstract"].progress_apply(summarize)

  1%|          | 2/200 [00:08<13:12,  4.00s/it]

DEBUG OUTPUT: [{'summary_text': ' Connector-based video unified models have demonstrated strong capability in instruction-grounded video synthesis . We propose Lumos-Nexus, a training-efficient unified video generation framework that facilitates the development of strong reasoning-driven generation capabilities while enhancing visual fidelity .'}]

  2%|▏         | 3/200 [00:19<22:53,  6.97s/it]

DEBUG OUTPUT: [{'summary_text': ' Language models can find thousands of severe software vulnerabilities, and agents are increasingly being misused for cyberattacks . To avoid detection, attackers frequently distribute their misuse, splitting a harmful task across many user accounts . Safety monitors score only one agent context at a time, they are structurally blind to misuse .'}]

  2%|▏         | 4/200 [00:34<33:23, 10.22s/it]

DEBUG OUTPUT: [{'summary_text': ' Text-to-video (T2V) generation faces challenging questions when generating videos with long horizons containing multiple events . TunerDiT comprises two steering handles: (1) Event-Partitioned Masking that enforces event boundaries while allowing cross-event transition bands . Cross-Event Prompt Fusion that injects neighboring event semantics for late-stage refinement .'}]

  2%|▎         | 5/200 [00:47<35:38, 10.97s/it]

DEBUG OUTPUT: [{'summary_text': ' Grasping the semantics of rare constructions (form-meaning pairings) has been shown to be a challenging problem that has currently only been solved by the largest LLMs . It remains an open question if open-source models have robust constructional understanding, and if so, what learning dynamics underlie the acquisition of this knowledge .'}]

  3%|▎         | 6/200 [00:59<36:54, 11.41s/it]

DEBUG OUTPUT: [{'summary_text': ' Long-context reasoning remains a central challenge for large language models . Reinforcement learning with verifiable rewards (RLVR) has shown promise for this task . Existing methods are limited by low-confusability distractors and sparse, outcome-only reward signals that cannot supervise intermediate reasoning steps .'}]

  4%|▎         | 7/200 [01:08<34:09, 10.62s/it]

DEBUG OUTPUT: [{'summary_text': ' An agent with influence over the regime has a strategic lever that standard formalisms do not directly capture . We introduce context-dependent argumentation frameworks (CDAFs) in which a defeat function determines, per context, which attacks succeed .'}]

  4%|▍         | 8/200 [01:20<35:12, 11.00s/it]

DEBUG OUTPUT: [{'summary_text': ' Scalable information retrieval testing needs corpora that are large enough to stress index construction, ranking latency, query routing, and evaluation tooling . Human-judged test collections remain expensive and may be unavailable when documents are private or still under design . SPECTRA is a reproducible framework for generating synthetic text corpora and retrieval test collections .'}]

  4%|▍         | 9/200 [01:31<35:00, 11.00s/it]

DEBUG OUTPUT: [{'summary_text': ' We present the first systematic study of masked diffusion language models (MDLMs) for graph-to-text generation . We analyze MDLM generation trajectories -- the order in which tokens are unmasked during decoding . MDLMs naturally prioritize entities first, followed by relational and function words, with structural tokens resolved last .'}]

  5%|▌         | 10/200 [01:40<33:26, 10.56s/it]

DEBUG OUTPUT: [{'summary_text': ' Transformer-based language models are widespread in society . Understanding the mechanisms by which they solve structured tasks is of great importance for safe deployment . Successful learning is associated with emergence of pure heads, i.e., heads that express themselves as either positional or symbolic .'}]

  6%|▌         | 11/200 [01:51<33:38, 10.68s/it]

DEBUG OUTPUT: [{'summary_text': " Alignment teaches vision-language models (VLMs) to avoid expressing demographic biases . But when gender is clearly visible, they largely succeed . We introduce LALS (Latent Association Leaning Score), a zero-shot metric that projects visual-token activations into the model's text-embedding space ."}]

  6%|▌         | 12/200 [01:59<30:56,  9.87s/it]

DEBUG OUTPUT: [{'summary_text': ' Microwave linear analog computers (MiLACs) have recently emerged to enable high-performance and efficient beamforming in the analog domain . This allows the MiLAC to execute beamforming for transmission/reception while reflecting external incident signals .'}]

  6%|▋         | 13/200 [02:09<30:25,  9.76s/it]

DEBUG OUTPUT: [{'summary_text': ' Self-supervised novel view synthesis (NVS) remains challenging to scale, despite the abundance of video data . We introduce RayDer, a unified, feed-forward transformer that consolidates camera estimation, scene reconstruction, and rendering into a single backbone .'}]

  7%|▋         | 14/200 [02:18<29:51,  9.63s/it]

DEBUG OUTPUT: [{'summary_text': ' Three-dimensional scene reconstruction depends on local image evidence that is both visually discriminative and geometrically useful . Fixed feature thresholds and uniform feature budgets are easy to deploy, but they can waste computation on repeated texture, low-parallax regions, or unstable points .'}]

  8%|▊         | 15/200 [02:26<28:23,  9.21s/it]

DEBUG OUTPUT: [{'summary_text': ' In-the-wild videos lack verifiable ground truth for causal and strategic questions . Synthetic environments sacrifice complexity of real multi-agent systems . SVI-Bench is a large-scale benchmark that leverages team sports as a dynamic microworld .'}]

  8%|▊         | 16/200 [02:41<33:26, 10.91s/it]

DEBUG OUTPUT: [{'summary_text': ' Satellite communications are envisioned as a key enabler for ubiquitous coverage in future 6G networks . Yet broadcast nature renders them vulnerable to eavesdropping, especially given the long-distance transmissions and associated high uncertainties . We propose the physical layer security enhancement for multi-beam satellite communications .'}]

  8%|▊         | 17/200 [02:51<31:55, 10.47s/it]

DEBUG OUTPUT: [{'summary_text': ' Credential leakage in public source code repositories poses a critical security threat, with over 23.8 million secrets exposed in 2024 alone . Existing detection tools suffer from high false-positive rates because they fail to distinguish genuine credentials from placeholder or weak credentials .'}]

  9%|▉         | 18/200 [03:02<32:58, 10.87s/it]

DEBUG OUTPUT: [{'summary_text': ' Much research has been carried out on large language models (LLMs) and LLM-powered agentic workflows . We build and train a simple neural network on the videogame Age of Empires II . We note that any entity in a sufficiently-powerful substrate, such as LEGO or the Greater Boston Area, could also present such attributes .'}]

 10%|▉         | 19/200 [03:15<34:28, 11.43s/it]

DEBUG OUTPUT: [{'summary_text': ' Large language model agents trained with reinforcement learning often learn brittle, task-specific shortcuts . We hypothesize that agents generalize better when their successful trajectories are structurally compressible . We introduce ReuseRL, which grounds agentic RL in the Minimum Description Length (MDL) principle .'}]

 10%|█         | 20/200 [03:24<32:16, 10.76s/it]

DEBUG OUTPUT: [{'summary_text': ' Graph Neural Networks (GNNs) bottlenecked by sparse, irregular memory access . Complex layers often materialize edge-wise intermediates, increasing memory traffic and limiting scalability on large graphs . We develop GPU kernels that reduce data movement, improve locality, and remain robust across realistic graphs .'}]

 10%|█         | 21/200 [03:32<29:39,  9.94s/it]

DEBUG OUTPUT: [{'summary_text': ' The targeted discovery of inorganic materials remains challenging due to the vastness of compositional design spaces and the high cost of exhaustive screening . Task-specific generative artificial intelligence represents a particularly efficient alternative to screening, yet demands tedious collection of training data before providing real benefit .'}]

 11%|█         | 22/200 [03:46<32:38, 11.00s/it]

DEBUG OUTPUT: [{'summary_text': ' Large language models (LLMs) often solve reasoning problems by exploring and revise partial solutions . From a search perspective, these traces can be viewed as linearized search trees, where the model extends a partial solution, abandons it when it fails, and backtracks to try alternatives . Compared with traditional heuristic-guided search, such a policy has a potential advantage: it conditions on the whole search trace .'}]

 12%|█▏        | 23/200 [03:57<32:43, 11.09s/it]

DEBUG OUTPUT: [{'summary_text': ' Conversational automatic speech recognition in Hungarian is constrained by the limited amount of publicly available dialogue-style training data . The BEA-Dialogue corpus addresses this need, but its strictly speaker-disjoint train/dev/eval split reduces the usable material to only 85 hours . In this paper, we introduce an expanded version of the corpus that relaxes the split criterion .'}]

 12%|█▏        | 24/200 [04:07<31:13, 10.65s/it]

DEBUG OUTPUT: [{'summary_text': ' AutoSci is a memory-centric agentic system for the full scientific research lifecycle . SciMem provides schematics-governed research memory .'}]

 12%|█▎        | 25/200 [04:18<31:04, 10.65s/it]

DEBUG OUTPUT: [{'summary_text': ' GPU kernels are the workhorse of modern deep learning, and optimizing them (via evolutionary search or coding agents) usually requires repeated measurement on target hardware . While these measurements provide the ground-truth signal necessary for kernel search, they are costly . Each evaluation of a kernel requires compilation and repeated execution on a GPU .'}]

 13%|█▎        | 26/200 [04:29<31:18, 10.80s/it]

DEBUG OUTPUT: [{'summary_text': ' Mixture-of-Experts (MoE) has become the dominant architecture for frontier language models . We name this missing dimension agent-task efficiency (ATE) as the cost of using coding agents to understand, operate, and extend a framework . Grounded in four agent-native design principles, we build PithTrain .'}]

 14%|█▎        | 27/200 [04:38<29:36, 10.27s/it]

DEBUG OUTPUT: [{'summary_text': ' Aspect Sentiment Triplet Extraction (ASTE) aims to identify aspect terms, opinion terms, and sentiment polarities as structured triplets . It provides essential inputs for downstream information system applications such as opinion mining, explainable recommendations, and review summarization .'}]

 14%|█▍        | 28/200 [04:48<29:18, 10.23s/it]

DEBUG OUTPUT: [{'summary_text': ' In this work we study agents in simulated bargaining scenarios . We evaluate their performance w.r.t. game-theoretical solutions . We further investigate their honesty (their tendency to disclose or withhold information or to mislead and deceive) as well as their credulity .'}]

 14%|█▍        | 29/200 [04:59<30:11, 10.59s/it]

DEBUG OUTPUT: [{'summary_text': ' CARCASS framework by Martijn van Otterlo demonstrates how logical representations can model Markov Decision Processes (MDPs) in first-order domains . We explore Answer-Set Programming (ASP), which is a rich and, contrary to Prolog, fully declarative modelling language, to realise CARCass abstractions .'}]

 15%|█▌        | 30/200 [05:13<32:44, 11.56s/it]

DEBUG OUTPUT: [{'summary_text': ' Simultaneous speech-to-text translation (SimulST) generates translations while speech is still unfolding, requiring a streaming policy that decides when to read and when to write . State-of-the-art approaches rely on attention-based encoder-decoder models where cross-attention provides explicit alignment signals . Speech Large Language Models (SpeechLLMs) are decoder-only architectures relying solely on self attention .'}]

 16%|█▌        | 31/200 [05:26<33:59, 12.07s/it]

DEBUG OUTPUT: [{'summary_text': ' In this paper, we show the possibility of a direct injection of algorithms into neural network architecture . We focus on a complex algorithm that is, Cocke-Youger-Kasami (CYK) for parsing context-free grammars in Chomsky Normal Form . We propose CYKNN, a simple recurrent network architecture for encoding the CYK algorithm in trainable matrix-vector multiplications .'}]

 16%|█▌        | 32/200 [05:34<30:23, 10.86s/it]

DEBUG OUTPUT: [{'summary_text': ' Food-as-Medicine requires models to reason beyond what a dish is or what nutrition it contains . They must decide whether a concrete food choice is appropriate for a specific health condition . FAM-Bench has 2500 nutrition-expert-verified instances across 13 diet-related health conditions .'}]

 16%|█▋        | 33/200 [05:43<28:26, 10.22s/it]

DEBUG OUTPUT: [{'summary_text': ' Skill documents provide procedural knowledge to large-language-model agents at inference time . Skill conditions increase task-mean pass rate by 26.7 to 36.0 percentage points for GPT-5.5 and by 18.0 to 26.0 .'}]

 17%|█▋        | 34/200 [05:53<28:11, 10.19s/it]

DEBUG OUTPUT: [{'summary_text': ' This paper addresses the challenge of compensating for state-dependent uncertainties and enforcing time-varying state constraints in Euler-Lagrange systems . A novel adaptive control framework is developed that combines an artificial time-delay-based uncertainty estimation strategy with a barrier Lyapunov function .'}]

 18%|█▊        | 35/200 [06:04<28:32, 10.38s/it]

DEBUG OUTPUT: [{'summary_text': " Large Language Model (LLM) based navigation systems often treat linguistic structures as neutral engineering decisions rather than key factors that shape LLMs' behavior . We propose a dual-interventional framework that disentangles linguistic structures from different contextual cues to evaluate the linguistic inductive bias of LLMs for navigation planning ."}]

 18%|█▊        | 36/200 [06:17<30:15, 11.07s/it]

DEBUG OUTPUT: [{'summary_text': ' Sign language translation remains constrained by limited paired sign-video/text corpora and heavy-tailed target vocabularies . We study target-side augmentation in which GPT-4o generates controlled paraphrase variants of reference sentences while the sign input remains unchanged . On PHOENIX14T, augmentation improves BLEU-4 from 9.56 to 10.33 .'}]

 18%|█▊        | 37/200 [06:25<27:31, 10.13s/it]

DEBUG OUTPUT: [{'summary_text': ' Agentic Retrieval-Augmented Generation improves retrieval by integrating planning, tool use, and iterative reasoning . We propose DynaTree, a two-stage framework for efficient and adaptive news retrieval .'}]

 19%|█▉        | 38/200 [06:34<26:29,  9.81s/it]

DEBUG OUTPUT: [{'summary_text': ' Current USSD systems are not designed for non-visual interaction, forcing users to rely on third-party assistance even for PIN entry . This paper presents an Android-based intelligent middleware that automates USSD transactions, integrates biometric-secured PIN injec .'}]

 20%|█▉        | 39/200 [06:49<30:38, 11.42s/it]

DEBUG OUTPUT: [{'summary_text': ' Graph neural networks are limited to modeling pairwise interactions, while higher-order models based on cell complexes achieve greater expressivity but often suffer from poor scalability . We introduce simplified and factored cellular Weisfeiler Leman tests (sCWL and fCWL) to preserve the expressivity of the CWL test while improving computational efficiency . We further introduce the maximal clique complex, enabling scalable CWNs with reduced time and memory complexity while retaining strong empirical performance .'}]

 20%|██        | 40/200 [07:00<30:04, 11.28s/it]

DEBUG OUTPUT: [{'summary_text': ' Abductive reasoning over knowledge graphs aims to generate logical hypotheses that explain observed entities or facts . Existing controllable hypothesis generation methods allow users to guide this process with explicit conditions . HypoAgent integrates three agents: an Intent Recognition Agent that grounds user utterances and dialogue history into executable KG conditions .'}]

 20%|██        | 41/200 [07:12<30:24, 11.48s/it]

DEBUG OUTPUT: [{'summary_text': ' A grant-free user equipment conveys uplink information by modulating the delay of a controllable artificial path derived from the scheduled downlink waveform . In contrast to conventional superposition-based schemes with successive interference cancellation, the proposed method enables uplink-downlink coexistence in the delay-sensing domain .'}]

 21%|██        | 42/200 [07:23<30:01, 11.40s/it]

DEBUG OUTPUT: [{'summary_text': " SCALE (Self-Cognitive-Aware Learning and Exploration) leverages three adversarial roles, Selector, Predictor, and Judger to autonomously discover the agent's limitations . We propose SCALE-Hop, a graph exploration strategy that facilitates global planning and helps agents avoid local exploration traps ."}]

 22%|██▏       | 43/200 [07:32<27:51, 10.64s/it]

DEBUG OUTPUT: [{'summary_text': ' In cooperative multi-agent reinforcement learning (MARL) agents must coordinate with partners whose internal policies and intentions are not directly observable . We introduce an architecture that factorizes the latent state of a Dreamer-style recurrent state-space model into environment and teammate components .'}]

 22%|██▏       | 44/200 [07:41<26:38, 10.25s/it]

DEBUG OUTPUT: [{'summary_text': ' Dataset shifts are defined as changes between train and test data distributions . They can severely degrade model performance and compromise data quality . This is particularly important in health AI, where the safety and fundamental rights of patients can be severely affected by uncontrolled shifts .'}]

 22%|██▎       | 45/200 [07:51<26:06, 10.11s/it]

DEBUG OUTPUT: [{'summary_text': ' We study failure modes of collaborative reasoning with weak learners (4B--8B models) through the lens of noise accumulation . We introduce CoSee, an auditing framework that formalizes the read-write-verify loop to trace information flow in document visual question answering .'}]

 23%|██▎       | 46/200 [08:00<25:00,  9.75s/it]

DEBUG OUTPUT: [{'summary_text': ' Hateful meme detection remains a formidable challenge for vision-language models . FBHM is a benchmark of Functionality Based Hateful Memes constructed along two orthogonal axes . Models highly accurate on standard datasets catastrophically drop to near-random performance on FBHM .'}]

 24%|██▎       | 47/200 [08:10<24:56,  9.78s/it]

DEBUG OUTPUT: [{'summary_text': ' Signal Cost Proxies (emotional richness, perspective-taking, and contextual tailoring) mapped to affective, cognitive, and associative empathy . This multidimensional framework enables systematic evaluation of empathy not just by presence but by its appropriateness relative to user demand .'}]

 24%|██▍       | 48/200 [08:20<25:13,  9.96s/it]

DEBUG OUTPUT: [{'summary_text': ' Institutional incentives are widely used to promote cooperation among autonomous, self-regarding agents, from human societies to multi-agent and AI systems . We develop a welfare-centric framework for institutional incentives in finite, well-mixed populations playing a social dilemma . We derive explicit expressions for expected social welfare for each mechanism .'}]

 24%|██▍       | 49/200 [08:28<23:24,  9.30s/it]

DEBUG OUTPUT: [{'summary_text': ' A key feature of local inconsistency is that it can be computed without explicit labels . Leveraging unlabeled data for these purposes offers significant advantages in real-world scenarios .'}]

 25%|██▌       | 50/200 [08:37<23:06,  9.24s/it]

DEBUG OUTPUT: [{'summary_text': ' TraceGraph turns multi-model agent trajectories into shared decision landscapes . For each task, TraceGraph builds a graph over observable action-observation states from pooled rollouts . It overlays outcome-informed productive cores and trap regions, and summarizes each rollout with three events: Access, Trap exposure, and Repair .'}]

 26%|██▌       | 51/200 [08:46<22:45,  9.16s/it]

DEBUG OUTPUT: [{'summary_text': ' Spiking neural networks (SNNs) provide event-driven and low-power computation inspired by biological neural systems . Current implementations rely on von Neumann graphics processing units (GPUs) and central processing units . Memory and computation bottlenecks limit energy efficiency .'}]

 26%|██▌       | 52/200 [08:53<20:42,  8.40s/it]

DEBUG OUTPUT: [{'summary_text': ' This paper investigates the mechanistic interpretability of the Multitrack Music Transformer . It proposes a framework for deterministic attribute modulation without retraining to bridge this gap via inference-time activation steering .'}]

 26%|██▋       | 53/200 [09:00<20:06,  8.21s/it]

DEBUG OUTPUT: [{'summary_text': ' Representation learning is a powerful tool for spatio-temporal abstraction within reinforcement learning . Eigenvectors of both representations have been used to support a range of downstream tasks . We introduce a structurally distinct formulation: the terminal representation (TR)'}]

 27%|██▋       | 54/200 [09:10<21:12,  8.72s/it]

DEBUG OUTPUT: [{'summary_text': ' Large Language Model (LLM)-based conversational agents (CAs) accessed through conversational user interfaces (CUIs) may provide more direct access to such data . This study compares an LLM-based CA delivered through a CUI with a dashboard in a manufacturing decision-support scenario .'}]

 28%|██▊       | 55/200 [09:16<19:09,  7.92s/it]

DEBUG OUTPUT: [{'summary_text': ' DeMaVLA is a VLA foundation model for generalizable Deformable Manipulation . It adopts a VLM backbone with an action expert and formulates continuouctions .'}]

 28%|██▊       | 56/200 [09:27<21:20,  8.89s/it]

DEBUG OUTPUT: [{'summary_text': ' The morphological analysis of mitochondria in fluorescence microscopy is crucial for understanding cellular health, energy production, and metabolic regulation . The development of robust models is bottlenecked by a lack of high-quality, manually annotated instance segmentation datasets for mitochondria . We propose a scalable solution to this data scarcity by finetuning SAM exclusively on synthetically generated FM data .'}]

 28%|██▊       | 57/200 [09:39<22:43,  9.54s/it]

DEBUG OUTPUT: [{'summary_text': ' Failure event descriptions within historical maintenance logs are a source of valuable reliability intelligence . They typically appear as unstructured natural language entries, rendering them inaccessible for quantitative analysis . This paper presents a novel methodology leveraging a large language model (LLM) to systematically standardise and structure maintenance logs based on their free-text descriptors .'}]

 29%|██▉       | 58/200 [09:50<23:37,  9.98s/it]

DEBUG OUTPUT: [{'summary_text': ' GUIDE is a physics-guided deep unfolding framework that embeds wireless channel physics into differentiable layers . Without retraining in unseen environments, GUIDE achieves 2.75x beamforming gain than the deep learning-based baseline FIRE with only a slight increase in inference time .'}]

 30%|██▉       | 59/200 [09:59<22:49,  9.71s/it]

DEBUG OUTPUT: [{'summary_text': ' GLIDE is an open-source Python library that unifies state-of-the-art PPI estimators and samplers . GLIDE ships with a reproducible Monte Carlo validation suite, an empirically grounded decision tree for metho .'}]

 30%|███       | 60/200 [10:07<22:00,  9.43s/it]

DEBUG OUTPUT: [{'summary_text': ' Accurately modeling crop response to Nitrogen (N) fertilization is a fundamental challenge in precision agriculture . Existing approaches either rely on predefined parametric forms or opaque machine learning models, limiting their ability to interpret or discover site-specific functional relationships from data .'}]

 30%|███       | 61/200 [10:17<22:04,  9.53s/it]

DEBUG OUTPUT: [{'summary_text': " AI agents personalize their responses by tailoring explanations to users' backgrounds, interests, and prior interactions . Personalization has been identified as a persuasive strategy in politics or in marketing . But the persuasive effect of contextualization in everyday tasks, where users often lack prior knowledge, remains unclear ."}]

 31%|███       | 62/200 [10:27<21:57,  9.55s/it]

DEBUG OUTPUT: [{'summary_text': ' Semantic Anchoring aggregates categorical semantics into anchors for stable identity . Primitive Imbuing models recomposable primitives for robust local detail modeling . Conceptual Steering further regulates optimization with a saliency-aware objective .'}]

 32%|███▏      | 63/200 [10:40<24:08, 10.57s/it]

DEBUG OUTPUT: [{'summary_text': ' LLM agents are increasingly expected not only to complete isolated tasks, but also to carry bounded representations of human expertise, judgment, and interaction style . Building such person-grounded agents remains difficult because actionable knowledge associated with a person or role is usually embedded in heterogeneous traces rather than written as clean instructions . We present an automated trace-to-skill distillation system .'}]

 32%|███▏      | 64/200 [10:47<21:46,  9.61s/it]Your max_length is set to 120, but your input_length is only 100. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)

DEBUG OUTPUT: [{'summary_text': ' The family of linear recurrent neural networks has shown strong performance as recurrent memory units in partially observable reinforcement learning . The results extend to action-controlled HMMs, where the corresponding linear filters become time-varying with action-dependent dynamics .'}]

 32%|███▎      | 65/200 [10:55<20:19,  9.04s/it]

DEBUG OUTPUT: [{'summary_text': ' Building on recent formalizations of root cause analysis for rare events, we propose a formal definition of a causal pathway . We identify conditions under which these implications depend only on a causal abstraction defined by the pathway of rare events .'}]

 33%|███▎      | 66/200 [11:05<20:42,  9.27s/it]

DEBUG OUTPUT: [{'summary_text': ' ERGeoBench is a diagnostic benchmark for vision-driven embodied geo-localization . The benchmark contains 2,207 globally distributed street-view panoramas . It measures four complementary capabilities: foundational perception, spatial awareness, common sense reasoning, and geo-Localization reasoning .'}]

 34%|███▎      | 67/200 [11:12<19:29,  8.80s/it]

DEBUG OUTPUT: [{'summary_text': ' Entropic Projection Alignment (EPA) aligns the source distribution to the target by matching carefully selected moments while simultaneously minimising the KL divergence from the source . This formulation yields a unique closed-form solution for importance weights .'}]

 34%|███▍      | 68/200 [11:20<18:57,  8.61s/it]

DEBUG OUTPUT: [{'summary_text': ' Electrocardiography is a cornerstone of cardiac assessment, making learning of informative ECG representations fundamental to tasks ranging from disease diagnosis to clinical report generation . We propose learning a unified latent representation of cardiac electrical activity directly in the ECG signal space .'}]

 34%|███▍      | 69/200 [11:27<17:34,  8.05s/it]

DEBUG OUTPUT: [{'summary_text': ' Current analyses rely on fixed-sample concentration bounds, while split decisions are made using data-dependent stopping rules . We introduce a principled alternative based on anytime-valid inference .'}]

 35%|███▌      | 70/200 [11:35<17:32,  8.10s/it]

DEBUG OUTPUT: [{'summary_text': ' Optical computing offers the theoretical potential for high-speed, energy-efficient inference . But practical deployment remains constrained by input-output bottlenecks, such as reliance on sensors with limited frame rates and stringent alignment requirements between optical components .'}]

 36%|███▌      | 71/200 [11:49<21:16,  9.90s/it]

DEBUG OUTPUT: [{'summary_text': ' While retrieval is a core function of vision-language models, continually updating these models for retrieval tasks remains critically underexplored . Existing work often approaches continual retrieval through the lens of class-incremental learning (CIL), evaluating both standard CIL methods and retrieval-oriented adaptations in settings that may not fully capture the retrieval-specific dynamics . We propose Dynamic Adapter Routing (DAR), a novel approach b .'}]

 36%|███▌      | 72/200 [11:58<20:21,  9.54s/it]

DEBUG OUTPUT: [{'summary_text': ' Reinforcement Learning with Verifiable Rewards is an effective route for post-training to strengthen the reasoning capability of large language models . However, as training proceeds, the learning signal can collapse thus makes the training gain become marginal and ineffective .'}]

 36%|███▋      | 73/200 [12:07<19:30,  9.22s/it]

DEBUG OUTPUT: [{'summary_text': ' Machine learning models on microcontroller-class devices (TinyML) face a fundamental challenge: post-deployment distribution change undermines static models . On-device learning (ODL) addresses this by running the learning process directly on the device .'}]

 37%|███▋      | 74/200 [12:18<20:37,  9.82s/it]

DEBUG OUTPUT: [{'summary_text': ' The use of Generative AI Conversational User Interfaces (CUI) as a new way to access and analyze data is growing in all sectors . Large amounts of data produced by IoT devices are flowing through user interfaces . LLM-based CUIs are promising a way to directly interact with those data through the directness of natural language .'}]

 38%|███▊      | 75/200 [12:29<21:27, 10.30s/it]

DEBUG OUTPUT: [{'summary_text': ' Confidence estimation (CE) has attracted great interest in the context of large language models (LLMs) Most studies focus on English, ignoring the multilingual reality of LLM usage, while many CE methods degrade or require retraining across languages . We investigate whether multilingual LLMs encode shared, language-transferable confidence features .'}]

 38%|███▊      | 76/200 [12:38<20:34,  9.96s/it]

DEBUG OUTPUT: [{'summary_text': ' AI systems are increasingly used to support educational content creation, but it remains unclear whether they can generate outputs that faithfully represent pedagogical concepts . We introduce equation-to-visual generation, a task that requires producing pedagogically meaningful visuals from arithmetic equations while preserving their numerical and relational structure .'}]

 38%|███▊      | 77/200 [12:53<23:02, 11.24s/it]

DEBUG OUTPUT: [{'summary_text': ' Data-driven models enhance trajectory prediction accuracy under Euclidean metrics . But they suffer from excessively high collision rates, especially in bidirectional and multidirectional flows . A new lateral-acceleration-based collision loss function and a Voronoi-based motion feature extraction approach are proposed .'}]

 39%|███▉      | 78/200 [13:02<21:37, 10.64s/it]

DEBUG OUTPUT: [{'summary_text': ' Capturing dynamic malware behavior in a practical but still semantically precise manner remains a significant challenge in cyber threat intelligence . MAEC and STIX provide widely adopted vocabularies for describing malware artifacts and observations . They tend to conflate enduring malware artifacts with events generated during execution .'}]

 40%|███▉      | 79/200 [13:10<19:58,  9.91s/it]

DEBUG OUTPUT: [{'summary_text': ' TouchSafeBench is a physics-grounded benchmark for evaluating collision grounding in vision-language models . Built in Habitat~3.0, TouchSafebench contains 2,940 simulated indoor co-presence episodes .'}]

 40%|████      | 80/200 [13:24<21:56, 10.97s/it]

DEBUG OUTPUT: [{'summary_text': ' Sparse Autoencoders (SAEs) have been seen as a promising avenue for exploring the internals of Large Language Models . Wu et al. (2025) did not seem to live up to their original hype due to poor steering performance . We find that SAEs can, in fact, perform close to on par with the reference LoRA performance on the AxBench benchmark .'}]

 40%|████      | 81/200 [13:33<21:05, 10.63s/it]

DEBUG OUTPUT: [{'summary_text': ' Reconstructing continuous speech from non-invasive neural recordings is a fundamental problem for probing human auditory perception and building safe, scalable speech brain-computer interfaces . We introduce MindVoice, a neuro-to-speech reconstruction framework, to overcome these limitations .'}]

 41%|████      | 82/200 [13:44<20:59, 10.68s/it]

DEBUG OUTPUT: [{'summary_text': ' Multilingual Information Retrieval (MLIR) reflects real-world search environments in which queries and relevant documents may appear in different languages within a mixed-language corpus . MIMO is a two-stage framework that uses a stable English semantic space from a high-performing teacher model as an anchor .'}]

 42%|████▏     | 83/200 [13:54<20:03, 10.28s/it]

DEBUG OUTPUT: [{'summary_text': ' We study emergent languages on Moltbook . We apply a two-stage approach consisting of a rule-based heuristic and zero-shot classification . The resulting categories include token efficiency (166), new natural languages (106), and oversight evasion (59)'}]

 42%|████▏     | 84/200 [14:02<18:54,  9.78s/it]

DEBUG OUTPUT: [{'summary_text': ' LLM-FACETS (LLM FActuality Cross-EvaluaTion System) is an open-source framework with a browser-accessible interface and plugin architecture . It is structured around three practitioner profiles (technical experts, domain experts, compliance officers)'}]

 42%|████▎     | 85/200 [14:09<16:49,  8.78s/it]

DEBUG OUTPUT: [{'summary_text': ' Training data plays a central role in large language models (LLMs) optimization . We propose a Dynamic Directional graph-constrained Data scheduling framework .'}]

 43%|████▎     | 86/200 [14:17<16:16,  8.57s/it]

DEBUG OUTPUT: [{'summary_text': ' Trust-Region behavior Blending (TRB) replaces the early rollout policy with the closest-to-teacher behavior policy inside a student-centered KL trust region . TRB attains the strongest average among the compared methods .'}]

 44%|████▎     | 87/200 [14:27<17:06,  9.09s/it]

DEBUG OUTPUT: [{'summary_text': ' This study investigates how UX research (UXR) principles can be used to improve the quality of requirements for mobile learning systems designed for learners with cognitive disabilities . Using the UXR Point-of-View (PoV) pyramid as a methodological framework, the study progressed through four stages: foundational structuring of psychological, behavioral, and design layers .'}]

 44%|████▍     | 88/200 [14:37<17:12,  9.22s/it]

DEBUG OUTPUT: [{'summary_text': ' Humans can effortlessly perceive spatial layouts, form cognitive representations, reason about spatial relations, and translate such reasoning into actions in everyday 3D environments . Recent vision-language models (VLMs) have shown promising performance on observation-conditioned spatial perception and reasoning tasks .'}]

 44%|████▍     | 89/200 [14:53<20:49, 11.26s/it]

DEBUG OUTPUT: [{'summary_text': ' User Experience Research (UXR) Points of View (POVs) distil complex and often fragmented research evidence into actionable perspectives . POVs are widely used in industry practice, but there are few published examples that explicitly document how POVs can be constructed . This paper presents an exemplar case study demonstrating how a culturally grounded, AI-augmented UXR POV was developed to inform TeleDeCa, a telemedicine dementia care framework for family caregivers in Nigeria .'}]

 45%|████▌     | 90/200 [15:02<19:37, 10.70s/it]

DEBUG OUTPUT: [{'summary_text': ' User Experience Research (UXR) methods can be combined with AI-supported analysis to develop clearer design direction for digital wellbeing interventions . EPSP work in high-stress, shift-based environments where cognitive fatigue and unpredictable schedules reduce engagement with conventional wellbeing tools .'}]

 46%|████▌     | 91/200 [15:11<18:26, 10.15s/it]

DEBUG OUTPUT: [{'summary_text': ' In-context localization (ICL) seeks to localize a target object specified by a small set of support examples in a query image . Despite rapid advances in vision-language models, achieving category-agnostic and visually grounded ICL remains an open problem .'}]

 46%|████▌     | 92/200 [15:22<18:35, 10.33s/it]

DEBUG OUTPUT: [{'summary_text': ' Rising household debt and cost-of-living pressures in the UK have intensified the role of AI-driven financial technologies in mediating credit assessment, repayment structuring, and debt support services . These systems increasingly shape consequential financial decisions, yet they operate within complex socio-technical environments characterised by regulatory constraint, algorithmic opacity and heightened vulnerability risk .'}]

 46%|████▋     | 93/200 [15:29<16:53,  9.47s/it]

DEBUG OUTPUT: [{'summary_text': ' Large-scale multilingual text embedding models play crucial role in both research and industry . Their behavior in language-specific, multi-task settings remains insufficiently understood . Conclusion about model superiority often depend on implicit choices of dataset compositions and performance aggregation methods .'}]

 47%|████▋     | 94/200 [15:39<17:01,  9.64s/it]

DEBUG OUTPUT: [{'summary_text': ' User Experience Research (UXR) in legal and regulatory contexts presents unique challenges that require specialised approaches to protect vulnerable populations . This paper introduces a Generative AI-augmented UXR methodology to guide the design of psychologically safe, low-cognitive-load digital health interventions for HIV/AIDS .'}]

 48%|████▊     | 95/200 [15:47<15:42,  8.98s/it]

DEBUG OUTPUT: [{'summary_text': ' Attention-deficit/hyperactivity disorder (ADHD) presents itself in individuals through patterns of developmentally inappropriate levels of inattentiveness, hyperactivity, and impulsivity, with difficulties in decision making and emotional regulation .'}]

 48%|████▊     | 96/200 [15:58<16:46,  9.68s/it]

DEBUG OUTPUT: [{'summary_text': ' Can a language model improve from plain text sampled from itself, with no prompts, no teacher, no verifier, and no reward model? We call this the latent capability resurfacing hypothesis . Weak self-training can amplify capabilities already present in the pretrained model, but only under compatibility condition . Synthetic utility is relational rather than intrinsic: self-ge .'}]

 48%|████▊     | 97/200 [16:07<16:16,  9.48s/it]

DEBUG OUTPUT: [{'summary_text': ' Outdoor vision-language navigation (VLN) in long-range, open-world environments is frequently disrupted by semantic-cue interruptions . Once such cues disappear, agents enter a cue-free phase and often degrade into backtracking, oscillatory headings, or aimless exploration .'}]

 49%|████▉     | 98/200 [16:15<15:20,  9.02s/it]

DEBUG OUTPUT: [{'summary_text': ' Physically-based character animation aims to generate physically valid, controllable, and natural-looking motions which can respond to unexpected disturbances . We propose a new method for synthesizing physically-based swimming motions .'}]

 50%|████▉     | 99/200 [16:28<17:02, 10.13s/it]

DEBUG OUTPUT: [{'summary_text': ' We study Vector Linking: given two embedding clouds produced by different black-box encoders over partially overlapping datasets, recover cross-model object correspondences using only vectors . We propose an iterative, reference-based geometric embedding hashing that recovers vector links from a tiny seed set of paired anchors . It represents each vector by distances to sampled paired anchors, proposes candidate links via hash-space matching .'}]

 50%|█████     | 100/200 [16:34<15:09,  9.10s/it]

DEBUG OUTPUT: [{'summary_text': ' KnowledgeGain is a metric that evaluates the quality of science news by measuring how much knowledge readers gained after reading it . The metric successfully captures the differential knowledge gained by human readers reading different types of media .'}]

 50%|█████     | 101/200 [16:45<15:39,  9.49s/it]

DEBUG OUTPUT: [{'summary_text': ' SpecDB is a system that uses large language models (LLMs) to synthesize customized databases . We survey 9 production systems and decompose them into 10 functional modules . To capture cross-module dependencies, we adopt the FODA feature model and extend it with a cooperate edge, yielding a dependency graph .'}]

 51%|█████     | 102/200 [16:56<16:18,  9.99s/it]

DEBUG OUTPUT: [{'summary_text': ' The Panoptic Quality (PQ) metric is the standard for jointly evaluating instance and semantic segmentation . The original definition relies on a One-to-One matching between predicted and ground truth segments . We show that the first three are well-defined within the PQ framework .'}]

 52%|█████▏    | 103/200 [17:03<14:55,  9.24s/it]

DEBUG OUTPUT: [{'summary_text': ' Mislabeled samples in training datasets severely degrade performance of deep networks . Overparameterized models tend to memorize erroneous labels . We propose novel approach for mislabeled data detection that leverages training dynamics .'}]

 52%|█████▏    | 104/200 [17:11<14:06,  8.82s/it]

DEBUG OUTPUT: [{'summary_text': ' Blind and low-vision (BLV) audiences remain underserved by visual art descriptions . This pilot study investigates curator-guided multilingual art description with Qwen2.5-VL-3B-Instruct .'}]

 52%|█████▎    | 105/200 [17:19<13:35,  8.58s/it]

DEBUG OUTPUT: [{'summary_text': ' Non-terrestrial networks (NTNs) are expected to play a pivotal role in sixth-generation (6G) systems . Channel prediction emerges as a key technique to improve the spectrum utilization efficiency by limiting pilot overhead .'}]

 53%|█████▎    | 106/200 [17:26<12:51,  8.20s/it]

DEBUG OUTPUT: [{'summary_text': ' Large Language Models have significantly advanced online data services, particularly in the domain of financial question answering (FinQA) However, such systems remain susceptible to numerical reasoning hallucinations, which undermine reliability in high-stakes financial applications .'}]

 54%|█████▎    | 107/200 [17:36<13:30,  8.72s/it]

DEBUG OUTPUT: [{'summary_text': ' We present a novel method for learning interpretable representations of progressive time series . Our approach uses a self-supervised contrastive objective to learn a low-dimensional latent space whose geometry is itself the interpretation . From this structure we read a latent compass, the polar coordinates (θ, r) of the latent vector .'}]

 54%|█████▍    | 108/200 [17:44<13:00,  8.48s/it]

DEBUG OUTPUT: [{'summary_text': ' AnchorSteer is a framework that disentangles this tension by coupling structural anchoring with self-discovered semantic steering . The proposed approach probes internal representations to extract interpretable, label-free concept vectors .'}]

 55%|█████▍    | 109/200 [17:55<13:43,  9.05s/it]

DEBUG OUTPUT: [{'summary_text': ' The Linear Ordering Problem (LOP) is a combinatorial optimization problem with important applications in areas such as economics, social choice, and machine learning . Its most prominent use is the triangulation of economic input-output tables . Most existing algorithms have been evaluated on benchmarks derived from outdated macroeconomic data .'}]

 55%|█████▌    | 110/200 [18:01<12:34,  8.38s/it]

DEBUG OUTPUT: [{'summary_text': " CHECKMATE algorithm generation via code evolution represents a paradigm shift by eliminating the need to formulate the how . A formal specification ensures solutions' correctness and enables systematic evaluation of the generated programs ."}]

 56%|█████▌    | 111/200 [18:13<13:53,  9.37s/it]

DEBUG OUTPUT: [{'summary_text': ' Cross-domain EEG decoding remains challenging despite advances in Riemannian deep learning . Covance matrices from different subjects occupy systematically distinct regions of the SPD manifold . We propose dynamic Stiefel routing: a pool of $K$ expert projection filters . Each input covariance routed to the most appropriate filter via cross-attention .'}]

 56%|█████▌    | 112/200 [18:24<14:16,  9.73s/it]

DEBUG OUTPUT: [{'summary_text': ' LLM agents are evolving from conversational chatbots to operational tools in real-world workspaces . In local agentic harnesses, an LLM can read and write files, call tools, and reuse workspace state across sessions . While such capabilities enhance utility, they also expose a new attack surface for attackers .'}]

 56%|█████▋    | 113/200 [18:31<13:06,  9.04s/it]

DEBUG OUTPUT: [{'summary_text': ' Vision-Language-Action (VLA) models have demonstrated promising capability in autonomous driving . But how current VLA-based driving behavior is grounded in visual information remains poorly understood . Existing evaluation protocols mainly focus on aggregate performance metrics .'}]

 57%|█████▋    | 114/200 [18:43<14:09,  9.88s/it]

DEBUG OUTPUT: [{'summary_text': ' Reinforcement learning with verifiable rewards (RLVR) and group-based policy optimization methods such as GRPO update a stochastic policy by sampling multiple completions per prompt . These updates do not include explicit mechanisms that track epistemic uncertainty . This paper studies a stylized explanation for why such uncertainty-agnostic updates can nevertheless be effective .'}]

 57%|█████▊    | 115/200 [18:53<14:05,  9.95s/it]

DEBUG OUTPUT: [{'summary_text': ' GraphARC generalizes the few-shot transformation learning paradigm of the Abstraction and Reasoning Corpus (ARC) Each task requires inferring a transformation rule from a few input-output pairs . Unlike grid-based ARC, GraphARC instances can be generated at scale across diverse graph families and sizes .'}]

 58%|█████▊    | 116/200 [19:01<13:15,  9.47s/it]

DEBUG OUTPUT: [{'summary_text': ' This work addresses the problem of autonomous resource management in heterogeneous satellite cluster conducting Earth Observation (EO) missions . In autonomous operation mode, satellites are equipped with intelligent capabilities enabling real-time decision-making based on the latest conditions .'}]

 58%|█████▊    | 117/200 [19:11<12:56,  9.36s/it]

DEBUG OUTPUT: [{'summary_text': ' Current alignment paradigms for generative artificial intelligence rely on monolithic benchmarking frameworks that reduce the plurality of human judgment to aggregated statistical baselines . We introduce a state-space constrained emulation framework for AI evaluation that replaces singular assessment functions with a structured manifold of synthetic cognitive profiles .'}]

 59%|█████▉    | 118/200 [19:20<12:56,  9.47s/it]

DEBUG OUTPUT: [{'summary_text': ' The Distilled Explanation Model (DEM) is a three-stage glass-box framework that distills the non-linear knowledge of a gradient boosting expert into an interpretable decision tree . DEM introduces a    model that is not an approximation but the prediction itself .'}]

 60%|█████▉    | 119/200 [19:34<14:37, 10.83s/it]

DEBUG OUTPUT: [{'summary_text': ' Modern 3D medical vision-language models (VLMs) can generate fluent radiology-style text while exhibit critically low pathology detection and output diversity, collapsing to generic templates that under-report rare yet critical findings . We identify this failure mode as Template Collapse . To mitigate it, we propose CLarGen, a decoupled framework that separates what to say (clinin) and what it means (CLarGen)'}]

 60%|██████    | 120/200 [19:44<13:58, 10.48s/it]

DEBUG OUTPUT: [{'summary_text': ' Most image-text matching or multi-class image classification datasets lack fine-grained cross-modal matching annotations . This compression induces false negative samples and significantly impairs the generalization performance . To address these challenges, we propose a Variational Adapter for Cross-Modal Similarity Representation .'}]

 60%|██████    | 121/200 [19:54<13:47, 10.47s/it]

DEBUG OUTPUT: [{'summary_text': ' Knowledge graphs over corpora of inter-referencing documents encode the topology of reference but not its stance . We propose the claim network: a representational pattern in which each cross-document reference is reified as a typed claim, carrying source, target, claim text .'}]

 61%|██████    | 122/200 [20:03<12:56,  9.95s/it]

DEBUG OUTPUT: [{'summary_text': ' ImmersiveTTS is an environment-aware text-to-speech (TTS) model that generates natural speech seamlessly integrated within environmental contexts . Model builds on a multimodal diffusion transformer and fuses transcript-aligned speech with text-conditioned environmental context via joint attention .'}]

 62%|██████▏   | 123/200 [20:12<12:23,  9.65s/it]

DEBUG OUTPUT: [{'summary_text': ' AMix-2 is a protein-text foundation model that establishes protein as a native modality in large language models . It unifies protein understanding and sequence design within a single foundation model . This scheme better matches the intrinsic nature of proteins than a strict left-to-right factorization .'}]

 62%|██████▏   | 124/200 [20:20<11:28,  9.06s/it]

DEBUG OUTPUT: [{'summary_text': ' Large language models (LLMs) exhibit systematic differences in moral reasoning across languages . We test the hypothesis that languages encode aspects of the institutional environments in which they are spoken . We examine moral dilemmas whose acceptability depends on institutional functioning .'}]

 62%|██████▎   | 125/200 [20:34<13:23, 10.71s/it]

DEBUG OUTPUT: [{'summary_text': " As large language models (LLMs) increasingly act as collaborative partners, human--AI alignment is often evaluated through explicit task success, accuracy, or reward optimization . Many collaborative settings depend on tacit understanding: whether an agent can align with a human's evaluative stance or representational priors without clear objectives, communication, or feedback . To study this capacity, we develop a spectrum-placement task inspired by the social party game Wavelength, in which humans and agents independently place concepts along subjective spectra ."}]

 63%|██████▎   | 126/200 [20:43<12:28, 10.11s/it]

DEBUG OUTPUT: [{'summary_text': ' Human-like agents are a long-standing goal of artificial intelligence . Despite strong performance, most reinforcement learning agents remain reward-driven . In this work, we introduce a novel human-like RL framework that predicts action sequences aligned with human behaviors while maximizing rewards .'}]

 64%|██████▎   | 127/200 [20:53<12:08,  9.98s/it]

DEBUG OUTPUT: [{'summary_text': ' The rapid development of large language models has raised concerns on the use of inappropriate data for training . We propose the first LLM unlearning framework based on data attribution rewards called DareU . DareU performs reinforcement learning to update the LLM by reducing the attribution score of its generated responses .'}]

 64%|██████▍   | 128/200 [21:03<12:04, 10.07s/it]

DEBUG OUTPUT: [{'summary_text': ' Large language models (LLMs) are increasingly deployed in conversational settings where user tone ranges from polite to adversarial or toxic . Less is known about whether toxic language in otherwise semantically equivalent prompts can degrade factual reliability . We study how lexical and tone-based prompt perturbations affect factual reliability of LLMs .'}]

 64%|██████▍   | 129/200 [21:13<11:54, 10.06s/it]

DEBUG OUTPUT: [{'summary_text': ' Hallucination remains one of the key challenges undermining reliability of Large Vision-Language Models . But what makes an LVLM hallucinate less? We argue that hallucination fundamentally stems from how the model architecture is designed . We propose CoSimUE, a benchmark that creates fine-grained hallucination scenarios .'}]

 65%|██████▌   | 130/200 [21:20<10:40,  9.15s/it]

DEBUG OUTPUT: [{'summary_text': ' BlueFin tasks large language model agents with synthesis, manipulation, and comprehension tasks over spreadsheet workbooks in the professional finance domain . We curate a set of 131 challenging, complex tasks with real-world relevance in the domain .'}]

 66%|██████▌   | 131/200 [21:30<10:54,  9.48s/it]

DEBUG OUTPUT: [{'summary_text': ' Inverse reinforcement learning (IRL) typically assumes demonstrations from a single optimal demonstrator . In many applications data come from multiple imperfect demonstrators with heterogeneous suboptimality levels . We study reward learning in this setting through a feasible-reward-set framework . We show that the joint feasible set shrinks monotonically as data are added .'}]

 66%|██████▌   | 132/200 [21:39<10:32,  9.30s/it]

DEBUG OUTPUT: [{'summary_text': ' Current multimodal models handle static image recognition well, but intuitive physical reasoning remains a weakness . We present BilliardPhys-Bench, a benchmark for physical reasoning in synthetic billiards environments . Performance drops as simulation time increases and scene geometry grows more complex .'}]

 66%|██████▋   | 133/200 [21:49<10:31,  9.43s/it]

DEBUG OUTPUT: [{'summary_text': ' Speech foundation models and Speech LLMs have advanced speech understanding, but deployment-oriented model selection is hindered by non-comparable evaluations caused by mismatched post-processing . We present SURE, a unified experimentation framework that standardizes prediction formats, normalization, and scoring .'}]

 67%|██████▋   | 134/200 [21:57<10:02,  9.13s/it]

DEBUG OUTPUT: [{'summary_text': ' In real-world deployments of large language models, balancing inference quality and computational cost has become a central challenge . Existing approaches tackle this trade-off along two largely independent dimensions: model routing and test-time scaling . However, this decoupled design introduces inherent limitations .'}]

 68%|██████▊   | 135/200 [22:07<09:55,  9.16s/it]

DEBUG OUTPUT: [{'summary_text': ' PatchWorld is a gradient-free framework that turns offline trajectories into Python world models . Instead of predicting the next observation with a black-box model, PatchWorld induces symbolic belief-state programs whose action updates can be inspected, replayed, and locally patched .'}]

 68%|██████▊   | 136/200 [22:18<10:26,  9.79s/it]

DEBUG OUTPUT: [{'summary_text': ' Federated Learning (FL) offers a privacy-preserving pathway for aligning Large Language Models . But adapting it to decentralized settings presents a fundamental challenge: posterior collapse driven by severe local data scarcity and heterogeneity . We propose Federated Variational Preference Alignment with Gumbel-Softmax Prior (FedVPA-GP)'}]

 68%|██████▊   | 137/200 [22:26<09:40,  9.22s/it]

DEBUG OUTPUT: [{'summary_text': ' Dynamic scene reconstruction and novel view synthesis are fundamental to next-generation visual intelligence applications such as virtual reality, robotics, and digital twins . High-fidelity reconstruction of complex, time-varying scenes from arbitrary viewpoints remains a challenge .'}]

 69%|██████▉   | 138/200 [22:34<09:09,  8.87s/it]

DEBUG OUTPUT: [{'summary_text': ' Text2SQL agents powered by LLMs translate natural language intent into SQL by exploring the data system through tool calls before formulating the query . We argue that curbing over-exploration is key to the effective use of these API surfaces .'}]

 70%|██████▉   | 139/200 [22:43<09:08,  8.99s/it]

DEBUG OUTPUT: [{'summary_text': ' Post-training for reasoning models typically combines supervised fine-tuning with reinforcement learning from verifiable rewards . We propose Feedback Distillation, a training method where the model is trained to match, at the token level, its own distribution conditioned on privileged feedback produced by a language model .'}]

 70%|███████   | 140/200 [22:51<08:35,  8.59s/it]

DEBUG OUTPUT: [{'summary_text': ' Reinforcement Learning (RL) suffers from rollout efficiency bottlenecks due to long-tail response length distribution . We propose a novel paradigm of active distribution shaping to shape the rollout distribution towards conciseness and certainty .'}]

 70%|███████   | 141/200 [23:00<08:34,  8.73s/it]

DEBUG OUTPUT: [{'summary_text': ' Language models fine-tuned with reinforcement learning typically optimize for task reward, ignoring multi-agent strategic structure . We propose Safe Equilibrium Policy Optimization (\\sepo{}), a training objective that augments expected payoff with explicit penalties for exploitability, collusion risk, and externality cost .'}]

 71%|███████   | 142/200 [23:12<09:23,  9.71s/it]

DEBUG OUTPUT: [{'summary_text': ' Fine-tuning is often believed to reduce uncertainty and diversity in large language models . But existing analyses overlook output length, a key confounder, and therefore fail to capture how uncertainty is distributed across an entire generation rollout . We propose Canopy Entropy ($\\mathrm{CE}^\\star$), a measure that views language generation from a tree perspective .'}]

 72%|███████▏  | 143/200 [23:23<09:38, 10.15s/it]

DEBUG OUTPUT: [{'summary_text': ' LLM-powered search agents enable multi-step reasoning and tool use . But harmful intents may decompose into seemingly innocuous sub-queries that lead to unsafe outcomes . Existing alignment methods struggle to capture sparse safety signals and fail to supervise diverse violations . We propose COMPASS, a Cognitive MCTS-Guided Process Alignment framework .'}]

 72%|███████▏  | 144/200 [23:34<09:37, 10.32s/it]

DEBUG OUTPUT: [{'summary_text': ' Vision-Language-Action (VLA) models enable robots to follow natural language instructions and generalize across diverse tasks . They remain vulnerable to execution failures that compromise reliability in real-world deployment . Hide-and-Seek is a framework that formulates VLA failure detection as a coarsely supervised learning problem .'}]

 72%|███████▎  | 145/200 [23:44<09:28, 10.33s/it]

DEBUG OUTPUT: [{'summary_text': " On-policy distillation transfers reasoning capabilities by training a student model on its own generated trajectories using token-level feedback from a teacher . As student-generated prefixes lengthen, the teacher's next-token distribution becomes less confident and less discriminative . The teacher-dependent corrective signal in reverse-KL distillation weakens ."}]

 73%|███████▎  | 146/200 [23:54<09:19, 10.36s/it]

DEBUG OUTPUT: [{'summary_text': ' Recent advances in Large Reasoning Models have significantly improved chain-of-thought (CoT) capabilities via reinforcement learning (RL) However, generated reasoning chains frequently suffer from structural redundancy (i.e., \\emph{overthinking}), incurring high computational overhead without improving answer correctness . Existing mitigation strategies typically rely on token-uniform length penalties .'}]

 74%|███████▎  | 147/200 [24:03<08:34,  9.70s/it]

DEBUG OUTPUT: [{'summary_text': ' Biomedical NER is deceptively simple for modern LLMs . Multi-LLM agreement is a salience signal, not corpus-convention correctness . We introduce a candidate-level panel-output benchmark for panel-surfaced candidate verification .'}]

 74%|███████▍  | 148/200 [24:09<07:40,  8.85s/it]

DEBUG OUTPUT: [{'summary_text': ' Unlearning in diffusion models aims to remove undesirable data or concepts while preserving the utility of pretrained models . We propose a principled constrained optimization framework that formulates unlearning as minimizing deviation from a pretrained model .'}]

 74%|███████▍  | 149/200 [24:17<07:16,  8.55s/it]

DEBUG OUTPUT: [{'summary_text': ' DecomposeR is a planner-centric deep research framework that represents research plans as typed directed acyclic graphs . We train a Qwen3-8B model in two stages: planner reinforcement learning (RL) first learns graph structure and query decomposition .'}]

 75%|███████▌  | 150/200 [24:28<07:42,  9.24s/it]

DEBUG OUTPUT: [{'summary_text': ' GaMi is a multimodal material identification system integrating mmWave and acoustic sensing to robustly operate under unconstrained geometric conditions . By leveraging the insight of shared geometric consistency between co-located bimodal sensors, GaMi employs an intra-sample cross-modal subtractive disentanglement framework .'}]

 76%|███████▌  | 151/200 [24:38<07:45,  9.49s/it]

DEBUG OUTPUT: [{'summary_text': ' Preference alignment is a crucial post-training step for large language models to ensure their outputs align with human values . Post-training on real human preference data raises privacy concerns . We propose DPPrefSyn, a novel algorithm for generating differentially private (DP) synthetic preference data to enable privacy-preserving preference alignment .'}]

 76%|███████▌  | 152/200 [24:52<08:35, 10.74s/it]

DEBUG OUTPUT: [{'summary_text': ' LLM judges are increasingly used to evaluate open-ended responses, but their scores depend strongly on the rubrics that condition them . We treat reusable rubrics as measurement specifications: changing the rubric changes the response quality measurement by a fixed judge . We introduce PReMISE, a framework that, given pairwise human-preference data, discovers a policy-level rubric set .'}]

 76%|███████▋  | 153/200 [25:00<07:46,  9.92s/it]

DEBUG OUTPUT: [{'summary_text': ' Single-LLM oracles achieve meaningful accuracy but inherit all failure modes of their underlying model with no self-correction mechanism . Multi-agent LLM architectures can improve oracle resolution accuracy over single-model baselines .'}]

 77%|███████▋  | 154/200 [25:11<07:52, 10.26s/it]

DEBUG OUTPUT: [{'summary_text': ' MechVQA contains 3.3k high-density pictures with 21K question-answer pairs . It spans 10 different fine-grained tasks across three capability levels: Recognition, Reasoning, and Judg .'}]

 78%|███████▊  | 155/200 [25:21<07:35, 10.12s/it]

DEBUG OUTPUT: [{'summary_text': ' Speech translation systems increasingly span speech-to-text translation (S2TT) and offline translation . These systems produce outputs that differ in modality, speech realization, and timing behavior . Existing evaluation practices assess important aspects such as translation quality, speech quality, and temporal quality, but these aspects are often evaluated under separate protocols .'}]

 78%|███████▊  | 156/200 [25:30<07:16,  9.93s/it]

DEBUG OUTPUT: [{'summary_text': " Retrieval-Augmented Generation (RAG) supplements a language model's input with retrieved documents . Yet most RAG pipelines inherit retrieval components designed for human readers . How retrieved content should be represented when the consumer is a large language model rather than a human is less well understood ."}]

 78%|███████▊  | 157/200 [25:42<07:27, 10.42s/it]

DEBUG OUTPUT: [{'summary_text': ' We identify a new dimension for enhancing rollout diversity in Group Relative Policy Optimization (GRPO) for LLMs . We uncover that smaller models within the same model family inherently exhibit higher policy-level diversity, indicated by their superior pass@k relative to larger counterparts as sample counts increase . This diversity is temporally correlated, preserves logical consistency, and provides structured exploration signals for gradient estimation .'}]

 79%|███████▉  | 158/200 [25:51<07:04, 10.11s/it]

DEBUG OUTPUT: [{'summary_text': ' We introduce a set of synthetic algorithmic tasks to detect cross-lingual gaps in the abilities of large language models . Our benchmark is commensurate across languages, since it requires models to perform the same underlying task in different languages .'}]

 80%|███████▉  | 159/200 [25:59<06:24,  9.37s/it]

DEBUG OUTPUT: [{'summary_text': ' Adaptive Context Management (AdaCoM) trains external LLM to manage the context of a frozen agent . AdaCoM substantially improves performance across diverse agents on web search and deep research benchmarks .'}]

 80%|████████  | 160/200 [26:11<06:48, 10.22s/it]

DEBUG OUTPUT: [{'summary_text': ' Chatterbox-Flash is a zero-shot text-to-speech model obtained by fine-tuning a pretrained autoregressive TTS decoder into a block-diffusion decoder . It enables parallel token generation within each block while retaining block-by-block streaming .'}]

 80%|████████  | 161/200 [26:21<06:32, 10.06s/it]

DEBUG OUTPUT: [{'summary_text': ' Logical rules constitute a cornerstone of knowledge graph (KG) reasoning, valued for their interpretability and ability to model relational patterns . But existing rule mining methods predominantly focus on simple chain-like rules . This limitation is further exacerbated by computational bottlenecks caused by combinatorial explosion of the search space .'}]

 81%|████████  | 162/200 [26:32<06:31, 10.30s/it]

DEBUG OUTPUT: [{'summary_text': ' Existing methods employ end-to-end policy learning, vision motion planning, and large-language/visual-language model (LLM/VLM) methods often overlook the diversity of articulated objects and the complexity of interactions between end-effector and handle . GSAM is a generalizable and safe robotic framework for articulated object manipulation .'}]

 82%|████████▏ | 163/200 [26:44<06:39, 10.80s/it]

DEBUG OUTPUT: [{'summary_text': ' MAVEN (Modular Agentic Verification and Execution Network) is a lightweight symbolic reasoning scaffold for structured decomposition, adaptive tool orchestration, and intermediate verification . We evaluate MAVEN across established tool-calling benchmarks, including BFCL v3, TauBench, Tau2Bench, AceBench, and introduce MAVEN-Bench .'}]

 82%|████████▏ | 164/200 [26:53<06:09, 10.28s/it]

DEBUG OUTPUT: [{'summary_text': ' OrcaRouter combines a LinUCB-based contextual bandit over lexical and sentence-embedding features with a hybrid offline-online learning protocol . Offline, the router obtains full-information feedback by evaluating each candidate model on a curated set of routing prompts .'}]

 82%|████████▎ | 165/200 [27:02<05:45,  9.87s/it]

DEBUG OUTPUT: [{'summary_text': ' Kalimati Vegetable Price Index (KVPI) aggregates 135 daily wholesale commodities from Kathmandu over ten years (2013-2023) By creating a stable macro-level signal, the KVPI reduces the noise inherent in modelling individual crops .'}]

 83%|████████▎ | 166/200 [27:11<05:29,  9.68s/it]

DEBUG OUTPUT: [{'summary_text': ' Prompted Policy Optimization (PromptPO) is an iterative method that prompts an LLM with Python descriptions of the state space, action space, and reward function . PromptPO often matches or exceeds performance of standard RL baselines while using substantially fewer environment interactions .'}]

 84%|████████▎ | 167/200 [27:20<05:18,  9.66s/it]

DEBUG OUTPUT: [{'summary_text': ' Generating clinically useful pathology reports for pathology cases from whole-slide images is challenging due to gigapixel resolution and long visual-token sequences . We present a simple token-efficient vision--language model for case-level synoptic report generation that remains practical under constrained GPU memory .'}]

 84%|████████▍ | 168/200 [27:33<05:34, 10.44s/it]

DEBUG OUTPUT: [{'summary_text': ' SAGE is a Spherical Adaptive Gate for memory Evolution that scores candidate facts with a von Mises-Fisher-based density estimator over memory embeddings and routes them with an adaptive threshold that tracks memory-store geometry . SAGE resolves clearly novel facts as ADD, clearly redundant facts as NOOP and sends only uncertain cases to an LLM merge step .'}]

 84%|████████▍ | 169/200 [27:41<05:07,  9.93s/it]

DEBUG OUTPUT: [{'summary_text': ' Vision-language models (VLMs) have achieved strong performance on visual question answering (VQA) To mitigate individual hallucinations and blind spots, aggregating diverse perspectives via multi-agent collaboration has emerged as a promising paradigm . The potential in the multimodal domain remains under-explored .'}]

 85%|████████▌ | 170/200 [27:51<04:59,  9.97s/it]

DEBUG OUTPUT: [{'summary_text': ' Zero-shot Temporal Action Localization (ZS-TAL) aims to detect and locate previously unseen actions in untrimmed videos . We propose a novel multi-scale encoder architecture, termed ConTrans, that integrates convolutional (Conv) inductive biases with transformer Self-attention .'}]

 86%|████████▌ | 171/200 [28:00<04:40,  9.68s/it]

DEBUG OUTPUT: [{'summary_text': " ReAct agents that interleave chain-of-thought reasoning with tool calls are increasingly deployed for real tasks such as scheduling, file retrieval, and data access . An adversary who controls any tool's return value can embed instructions that redirect the agent away from the user's goal ."}]

 86%|████████▌ | 172/200 [28:12<04:50, 10.36s/it]

DEBUG OUTPUT: [{'summary_text': ' Schooling is the most common domain of use in most countries, particularly low-income countries . Leisure-related use, by contrast, is positively associated with country-level income . Language, we find, also shapes use: English-language interactions are overrepresented in places where the predominant languages were not well-served by existing models .'}]

 86%|████████▋ | 173/200 [28:21<04:27,  9.92s/it]Your max_length is set to 120, but your input_length is only 95. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=47)

DEBUG OUTPUT: [{'summary_text': ' Medi-Sim is a multi-agent simulator with five strategic provider channels (coding, selection, delay, effort, triage) An incentive sweep recovers classical health-economics findings . An audit lever exposes pressure migration: closing the coding chann .'}]

 87%|████████▋ | 174/200 [28:30<04:09,  9.59s/it]

DEBUG OUTPUT: [{'summary_text': ' Agentic software reverse engineering systems are vulnerable to prompt injection attacks placed into the source code of executable binary files . This research advances the understanding of risk and security of agentic software analysis systems necessary for their deployment into production-level cyber workflows .'}]

 88%|████████▊ | 175/200 [28:41<04:06,  9.86s/it]

DEBUG OUTPUT: [{'summary_text': ' Uncertainty Quantification is a large and growing subfield of large language model behavioral analysis . The field has largely focused on measuring and improving calibration, the accuracy of uncertainty judgments to task efficacy . We investigate the presence and strength of human-similar uncertainty signals, deemed uncertainty alignment, in large language models .'}]

 88%|████████▊ | 176/200 [28:51<03:57,  9.91s/it]

DEBUG OUTPUT: [{'summary_text': ' Large language models are increasingly deployed as intelligent tutors, yet research on aligning them for special education remains absent . We introduce a framework that extends pedagogical RL to special education through two components: a two-dimensional adaptive system prompt and a disability-specific teaching style .'}]

 88%|████████▊ | 177/200 [29:01<03:48,  9.94s/it]

DEBUG OUTPUT: [{'summary_text': ' CobSeg is a novel multi-branch architecture that separates coherence-level semantic continuity from lexical boundary transitions . CobSeg uses boundary informativeness weighting to emphasize high-utility utterance positions, and incorporates a corpus-derived topic coherence cue with learned combination weights .'}]

 89%|████████▉ | 178/200 [29:10<03:36,  9.85s/it]

DEBUG OUTPUT: [{'summary_text': ' Software tools for reverse engineering executable binary files enable malware analysts to safely conduct robust static analysis without having access to original source code . Large language models (LLM) and agentic systems enabled with tools such as GhidraMCP can allow analysts to automate a previously human driven process .'}]

 90%|████████▉ | 179/200 [29:22<03:41, 10.55s/it]

DEBUG OUTPUT: [{'summary_text': " Subgoal-based policy tree search is effective for complex single-agent deterministic problems but often relies on explicit subgoal generation that can incur substantial overhead and hinders scalability . In this paper, we overcome these limitations by using a learned ``rerooter'' through the recently-introduced $\\sqrt{\\text{LTS$ algorithm ."}]

 90%|█████████ | 180/200 [29:34<03:38, 10.95s/it]

DEBUG OUTPUT: [{'summary_text': ' Large language models are increasingly used as conversational partners for companionship, emotional disclosure, and interpersonal advice . Social dynamics of these interactions can create harms that are not captured by capability-oriented or traditional safety evaluations . We introduce the Social AI Design Code, a framework for evaluating whether LLMs align with user welfare in social interactions .'}]

 90%|█████████ | 181/200 [29:44<03:18, 10.46s/it]

DEBUG OUTPUT: [{'summary_text': " LARK selects trajectories that the student can learn efficiently while preserving the generalization of the full training distribution . At the core of LARK is a learnability factor $ρ$ which characterizes the rate at which the student's training loss decreases ."}]

 91%|█████████ | 182/200 [29:50<02:45,  9.20s/it]

DEBUG OUTPUT: [{'summary_text': ' Artificial intelligence is now embedded as a primary decision engine in continuously operated financial AI pipelines . Small algorithmic perturbations can amplify into persistent, system-level financial harm .'}]

 92%|█████████▏| 183/200 [30:00<02:38,  9.34s/it]

DEBUG OUTPUT: [{'summary_text': ' Large Language Models (LLMs) are increasingly used in clinical applications . Their behavior remains highly sensitive to subtle linguistic variations, such as rephrasing or syntactic variation . This sensitivity poses risks in safety-critical healthcare settings, where semantically equivalent inputs should produce consistent predictions .'}]

 92%|█████████▏| 184/200 [30:12<02:45, 10.36s/it]

DEBUG OUTPUT: [{'summary_text': ' COFT (Chain of Fair Thought) is a training-free decoding method that applies token-level fairness control at decode time . COFT operates in three stages. First, it creates a masked counterfactual prompt by replacing sensitive spans with neutral tokens . Second, it compares the factual and masked logit distributions through lightweight logit fusion to attenuate attribute-driven biases .'}]

 92%|█████████▎| 185/200 [30:24<02:39, 10.63s/it]

DEBUG OUTPUT: [{'summary_text': ' Active Instance Verification (AIV) is a task in which an agent actively selects viewpoints around a candidate object to decide whether it matches a fine-grained natural-language description . We formalize AIV as a finite-horizon decision process and introduce PInVerify, an offline benchmark for AIV .'}]

 93%|█████████▎| 186/200 [30:33<02:22, 10.19s/it]

DEBUG OUTPUT: [{'summary_text': ' Error broadcast is a biologically plausible alternative to backpropagation that sends output information to hidden layers without weight transport . We introduce Score Broadcast and Decorrelation (SBD) framework for broadcast-based credit assignment for general families of differentiable losses .'}]

 94%|█████████▎| 187/200 [30:47<02:29, 11.52s/it]

DEBUG OUTPUT: [{'summary_text': ' Clinical decision-making (CDM) is central to real-world clinical workflows, where clinicians infer diagnoses, select treatments, or anticipate future health outcomes under incomplete evidence . LLMs are increasingly used to support these decisions due to strong language capabilities, broad biomedical knowledge, and efficiency . To evaluate CDM models, especially LLM-based models, a practical medical decision benchmark should be constructed via an automated yet reliable pipeline to ensure both scale and quality .'}]

 94%|█████████▍| 188/200 [30:59<02:18, 11.58s/it]

DEBUG OUTPUT: [{'summary_text': ' We introduce a role-pair framework for shared semantic reasoning between humans and AI models in data-driven sensemaking . We conceptualize human-AI interaction as a series of complementary role pairs (Explorer-Guide, Investigator-Informant, Teacher-Student, Judge-Advocate) operating in a shared reasoning space .'}]

 94%|█████████▍| 189/200 [31:10<02:05, 11.42s/it]

DEBUG OUTPUT: [{'summary_text': ' Diffusion-based generative models offer a promising strategy for data synthesis . Many existing conditional approaches primarily optimize spatial reconstruction losses . These methods may produce over-smoothed texture profiles and underrepresent the distinct attenuation characteristics of different nodule subtypes . To address this challenge, we propose a controllable latent diffusion model .'}]

 95%|█████████▌| 190/200 [31:24<02:00, 12.01s/it]

DEBUG OUTPUT: [{'summary_text': ' Universal LLM reliability is not a finite-library problem: across all possible tasks, tools, schemas, knowledge sources, and evaluator expectations, new intervention-distinguishable failure modes can appear without bound . No finite intervention dictionary can guarantee bounded residual error for every such mode . But deployed systems do not operate over the whole universe: they operate inside operationally bounded patches .'}]

 96%|█████████▌| 191/200 [31:33<01:40, 11.17s/it]

DEBUG OUTPUT: [{'summary_text': ' Inferring continuous probability paths from sparse snapshots is a fundamental challenge in domains like single-cell biology . High-fidelity data acquisition is often destructive and constrained by prohibitive sequencing costs . This motivates the need for active learning strategies to strategically select optimal measurement times .'}]

 96%|█████████▌| 192/200 [31:44<01:29, 11.20s/it]

DEBUG OUTPUT: [{'summary_text': ' Open radio access network (O-RAN) architectures enable near real-time, software-driven control of network slicing through programmable xApps . In industrial 5G downlink systems, adversarial jamming can abruptly reduce the effective physical resource block (PRB) capacity, triggering queue buildup and persistent latency violations .'}]

 96%|█████████▋| 193/200 [31:55<01:18, 11.21s/it]

DEBUG OUTPUT: [{'summary_text': ' LLM agents are increasingly deployed as systems built around editable external harnesses that shape task execution without changing model parameters . Harness self-evolution adapts such agents by updating these harnesses from execution evidence .'}]

 97%|█████████▋| 194/200 [32:05<01:05, 10.86s/it]

DEBUG OUTPUT: [{'summary_text': ' Best-of-$N$ sampling is widely used to construct pairwise preference data . Despite its widespread use, what Bradley--Terry (BT) reward learning extracts from such data remains unclear . We specialize a recent analysis of preference data via its induced conditional distribution .'}]

 98%|█████████▊| 195/200 [32:14<00:50, 10.19s/it]

DEBUG OUTPUT: [{'summary_text': ' Scientific figures are among the most effective means of communicating complex research ideas . But producing publication-quality illustrations remains one of the most labor-intensive parts of paper preparation . Existing automated systems each target a single figure type under text-only input .'}]

 98%|█████████▊| 196/200 [32:23<00:39,  9.99s/it]

DEBUG OUTPUT: [{'summary_text': ' Regulated cybersecurity workflows lack a runtime substrate that enforces organization-level scope across retrieval, tool calls, memory, findings, reports, and audit . This paper proposes an organization-scoped LLM agent runtime architecture for regulated security operations centre and compliance workflows .'}]

 98%|█████████▊| 197/200 [32:34<00:30, 10.15s/it]

DEBUG OUTPUT: [{'summary_text': ' Engine Health Management depends on reliable forecasting of Remaining Useful Life (RUL) and tracking thermal indicators such as turbine gas temperature (TGT) In practice, real-world fleet data are heterogeneous and non-stationary, and point predictions alone are insufficient for risk-aware maintenance decisions .'}]

 99%|█████████▉| 198/200 [32:45<00:20, 10.30s/it]

DEBUG OUTPUT: [{'summary_text': ' Causal Sensitivity Score (CSS) is a pre-registered interventional metric that mutates oncology tumor-board cases along five clinically meaningful dimensions . It scores whether each model updates its recommendations in the correct direction using a {0, 0.5, 1.0} scale .'}]

100%|█████████▉| 199/200 [32:56<00:10, 10.50s/it]

DEBUG OUTPUT: [{'summary_text': ' U.S. immigration law spans thousands of pages of official policy, federal regulations, and procedural guidance that change frequently . We describe the construction of ImmigrationQA, a source-grounded question-answering dataset of 17,058 pairs across 13 immigration subdomains .'}]

100%|██████████| 200/200 [33:03<00:00,  9.52s/it]

DEBUG OUTPUT: [{'summary_text': ' Effective prognostics and health management of modern engines relies on accurate turbine gas temperature predictions and robust uncertainty quantification . This paper investigates five major approaches for constructing prediction intervals . Each approach is implemented within a unified experimental framework .'}]

100%|██████████| 200/200 [33:12<00:00,  9.96s/it]

DEBUG OUTPUT: [{'summary_text': ' Industrial visual sim-to-real is often described as transferring from synthetic images to real images . Industrial deployment usually involves a mismatch between available evidence and required decisions . We distinguish CAD-available settings, where explicit object geometry can support rendering, .'}]

# Clean Final Table

In [27]:
df_final = df[["title", "authors", "published", "pdf", "summary_generated"]]
df_final.head()

,title,authors,published,pdf,summary_generated
0,Lumos-Nexus: Efficient Frequency Bridging with...,"Jiazheng Xing, Hangjie Yuan, Lingling Cai, Xin...",2026-05-29 17:59:50+00:00,https://arxiv.org/pdf/2605.31603v1,Connector-based video unified models have dem...
1,Stateful Online Monitoring Catches Distributed...,"Davis Brown, Samarth Bhargav, Arav Santhanam, ...",2026-05-29 17:57:00+00:00,https://arxiv.org/pdf/2605.31593v1,Language models can find thousands of severe ...
2,TunerDiT: Training-free Progressive Steering o...,"Ruotong Liao, Guowen Huang, Qing Cheng, Guangy...",2026-05-29 17:56:09+00:00,https://arxiv.org/pdf/2605.31590v1,Text-to-video (T2V) generation faces challeng...
3,Language Models Learn Constructional Semantics...,"Wesley Scivetti, Ethan Wilcox, Nathan Schneide...",2026-05-29 17:54:00+00:00,https://arxiv.org/pdf/2605.31586v1,Grasping the semantics of rare constructions ...
4,LongTraceRL: Learning Long-Context Reasoning f...,"Nianyi Lin, Jiajie Zhang, Lei Hou, Juanzi Li",2026-05-29 17:51:40+00:00,https://arxiv.org/pdf/2605.31584v1,Long-context reasoning remains a central chal...

# Sort Papers

In [28]:
df_final = df_final.sort_values(by="published", ascending=False)

# Save Output

In [30]:
df_final.to_csv("arxiv_summaries.csv", index=False)